# Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [4]:
import numpy as np

# create array using numpy
# create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
# 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:

# Attributes of NumPy
arr=np.array([[1,2,3],[4,5,6]])

print("Array: ",arr)
print("Shape: ",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements): ",arr.size)
print("Data type: ",arr.dtype)
print("Items size (in bytes): ",arr.itemsize)

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Items size (in bytes):  8


In [16]:
# Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element Wise addition
print("Addition: ",arr1+arr2)

# Element Wise substraction
print("Substraction: ",arr1-arr2)

# Element Wise multiplication
print("Multiplication: ",arr1*arr2)

# Element Wise division
print("Division: ",arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [17]:
# Universal Function
arr=np.array([2,3,4,5,6])
# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
# Array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [30]:
print(arr[0][3])
print(arr[0:2,2:])

4
[[3 4]
 [7 8]]


In [26]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [33]:
# Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [34]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [35]:
# Statistical concepts -- Normalization

data=np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

# Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
# Mean
mean=np.mean(data)
print("Mean: ",mean)
 
# Median
median=np.median(data)
print("Median: ",median)
 
# Standard Deviation
std_dev=np.std(data)
print("Standard Deviation: ",std_dev)
 
# Variance
variance=np.var(data)
print("Variance: ",variance)
 

Mean:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951
Variance:  2.0


In [41]:
# Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])